### ISSUE TITLE
Import with blank pages

### ISSUE THREAD

**Issue by rener-rannieri** [aoout/obsidian-epub-importer#24] opened 2024-01-10 14:44 UTC
Hey, nice plugin!

I've configured everything correctly, and the book is imported with all the chapters, but all the pages are blank, without any content, text, or images. I've tested with several .epub files and in 2 different vaults.

I'm on Linux based Ubuntu with Gnome (Zorin OS 17) - I thought it might be some library dependency issue, so I installed Calibre, Foliate, and Koodo. But it still has the same error - it imports all the empty chapters.

Do you have any idea what could be the problem?

I'm about to install a dual-boot with Windows to use this plugin - I'm creating an incremental reading system, and being able to import an .epub into Obsidian in chapters would greatly help for adding spaced repetition.

Looking forward to your response and great job.

**Comment by RenerRanni** [comment] 2024-01-11 13:35
![Captura de tela de 2024-01-11 10-22-39](https://github.com/aoout/obsidian-epub-importer/assets/96302628/0c5a665b-f75e-40f1-ab49-347d7c6a616f)

![image](https://github.com/aoout/obsidian-epub-importer/assets/96302628/b5bb3ed1-1f72-4c72-914a-536dc1dc7898)

Books: [Epub-Exemple.zip](https://github.com/aoout/obsidian-epub-importer/files/13903840/Epub-Exemple.zip)

**Comment by aoout** [comment] 2024-01-12 10:54
I imported `Andy Weir - Devoradores de estrelas(Z-Lib.io).epub` on windows successfully and everything works fine.
I guess I'm a little confused now too.

**Comment by ryran** [comment] 2024-01-18 00:47
Same issue for me, for everything I've tried to import. For example:

- https://www.bahaiebooks.org/publications/messageonworldpeace2019/
- https://www.bahaiebooks.org/publications/peacecompilation/
- https://www.bahaiebooks.org/publications/hiddenwords/
- https://www.bahaiebooks.org/publications/summonsoflordofhosts/
- https://www.bahaiebooks.org/publications/bahaiprayers/

And to be clear, I've used these ePub files with other readers -- most recently, I have them all loaded up into Google Play Books.

**Comment by aoout** [comment] 2024-01-18 03:00
@RenerRanni @ryran 
I'm using windows, how can I debug code on linux? Know of any good method?

**Comment by aoout** [comment] 2024-03-18 09:30
It seems there is nothing I can do to provide any help with this problem.

**Comment by aoout** [comment] 2024-05-26 15:08
/

**Comment by aoout** [comment] 2024-05-26 15:10
Duplicate of #63

**Closed** 2024-05-26 15:11 UTC
Labels: bug, linux, feature bug
