### ISSUE TITLE
无法解析特定的epub文件

### ISSUE THREAD

**Issue by chengsuen** [aoout/obsidian-epub-importer#47] opened 2024-04-02 02:04 UTC
%%please test the bug in a black vault first.
%%if there is something on console, please upload the screenshot.
![屏幕截图 2024-04-01 201732](https://github.com/aoout/obsidian-epub-importer/assets/165742339/57da3462-02d8-4708-978e-1da71c906a92)

（其实是我这边手头所有的epub都没法解析

**Comment by aoout** [comment] 2024-04-04 07:24
@net-frog
What version of the plugin are you using? I didn't find this problem on 0.3.1-beta.1

**Comment by aoout** [comment] 2024-04-04 07:25
Please upload .epub file.

**Comment by aoout** [comment] 2024-04-05 13:42
@net-frog 
You can get beta through brat.

I just tested on 0.3.0 and everything works equally well.
Which OS are you using?

**Comment by net-frog** [comment] 2024-04-06 09:56
I have tested with the 0.3.1beta, the epub is imported successfully but all the notes are empty although each note is named as the chapter name in the epub.  Also, after deleting the book folder I cannot import the same epub again, it says duplicate folder exists.

**Comment by aoout** [comment] 2024-04-06 10:26
@net-frog 
Sorry, but I can't reproduce your situation. 
I retried the import again and everything worked fine and the content displayed normally.

**Comment by net-frog** [comment] 2024-04-08 09:51
I have tested on 3 different systems it seems there is some underlining bug. If I have base obsidian installer 1.4.13 but have catalyst update to 1.5.12, on one system it works without issue. However, if the base installer is updated to latest 1.5.12 the 
following error is thrown. Please check with updated installer 1.5.12

 
![image](https://github.com/aoout/obsidian-epub-importer/assets/35987262/67a5a02b-c232-49fd-853c-4d1993b67046)

**Comment by aoout** [comment] 2024-04-13 07:50
@net-frog 
I understand, the newer installer brought newer nodejs, and one of the modules I was using had a bug on the newer nodejs, so this all happened.
Reference: https://github.com/ZJONSSON/node-unzipper/issues/286

**Comment by aoout** [comment] 2024-04-13 07:51
I have replaced it with another module and released version 0.3.1.

**Comment by aoout** [comment] 2024-04-13 07:52
@chengsuen 
请下载0.3.1版本进行尝试

**Comment by aoout** [comment] 2024-04-21 06:24
I'll close the issue for now. If the bug still exists, please reopen this issue.

**Closed by aoout** 2024-04-21 06:24 UTC
Labels: bug, enhancement, feature bug, better parser
